---
# tasks file for ansible_role_docker-compose

- name: "PIP | Ensure that python 2.7 is installed"
  yum:
    name: python
    state: present
  tags:
    - install

- name: "Docker-Compose | Install docker-compose"
  yum:
    name: docker-compose
    state: present
  tags:
    - install
