---
# tasks file for ansible_role_docker-compose

- name: "Docker-Compose | Ensure that python 2.7 is installed"
  yum:
    name: python
    state: present
  tags:
    - docker
    - compose
    - install

- name: "Docker-Compose | Install urllib3"
  pip:
    name: urllib3
  tags:
    - docker
    - compose
    - install

- name: "Docker-Compose | Install docker-compose"
  yum:
    name: docker-compose
    state: present
  tags:
    - docker
    - compose
    - install
